CREATE TABLE TAGAI (
    ID    INTEGER NOT NULL,
    NAME  VARCHAR(15) CHARACTER SET ISO8859_13 COLLATE LT_LT
);
ALTER TABLE TAGAI ADD CONSTRAINT PK_TAGAI PRIMARY KEY (ID);

CREATE TABLE KLIENTAI (
    KLIENTOID             INTEGER NOT NULL,
    PAVADINIMAS           VARCHAR(20) CHARACTER SET ISO8859_13,
    TAGID                 INTEGER,
    TAGID2                INTEGER
);
ALTER TABLE KLIENTAI ADD CONSTRAINT PK_KLIENTAI PRIMARY KEY (KLIENTOID);
ALTER TABLE KLIENTAI ADD CONSTRAINT FK_KLIENTAI_2 FOREIGN KEY (TAGID) REFERENCES TAGAI (ID);
ALTER TABLE KLIENTAI ADD CONSTRAINT FK_KLIENTAI_3 FOREIGN KEY (TAGID2) REFERENCES TAGAI (ID);
