CREATE TABLE tagai (
    ID    INTEGER NOT NULL,
    NAME  VARCHAR(15)
);
ALTER TABLE tagai ADD CONSTRAINT PK_TAGAI PRIMARY KEY (ID);

CREATE TABLE klientai (
    KLIENTOID             INTEGER NOT NULL,
    PAVADINIMAS           VARCHAR(20) ,
    TAGID                 INTEGER,
    TAGID2                INTEGER
);
ALTER TABLE klientai ADD CONSTRAINT PK_KLIENTAI PRIMARY KEY (KLIENTOID);
ALTER TABLE klientai ADD CONSTRAINT FK_KLIENTAI_2 FOREIGN KEY (TAGID) REFERENCES tagai (ID);
ALTER TABLE klientai ADD CONSTRAINT FK_KLIENTAI_3 FOREIGN KEY (TAGID2) REFERENCES tagai (ID);
